fields_with_nums = ["ctf_funding_usd","lifetime_where_available", "expected_ghg_reductions_lifetime_tco2",
                    "expected_ghg_reductions_annual_tco2_yr", "expected_co_financing_total_us_m",
                    "expected_co_financing_mdb1_us_m", "expected_co_financing_govt_us_m",
                    "expected_co_financing_pvt_us_m", "expected_co_financing_bilateral_us_m",
                    "expected_co_financing_others_us_m", "expected_installed_capacity_total_mw",
                    "expected_installed_capacity_wind_mw", "expected_installed_capacity_solar_mw",
                    "expected_installed_capacity_hydro_mw", "expected_installed_capacity_geothermal_mw",
                    "expected_installed_capacity_mixed_mw",
                    "expected_additional_passengers_upon_implementation_passengers_per_day",
                    "expected_energy_savings_annual_gwh_yr", "actual_2015_ghg_reductions_annual_tco2_yr",
                    "actual_2015_co_financing_total_us_m", "actual_2015_co_financing_mdb1_us_m",
                    "actual_2015_co_financing_govt_us_m", "actual_2015_co_financing_pvt_us_m",
                    "actual_2015_co_financing_bilateral_us_m",
                    "actual_2015_co_financing_others_us_m", "actual_2015_installed_capacity_total_mw",
                    "actual_2015_installed_capacity_wind_mw", "actual_2015_installed_capacity_solar_mw",
                    "actual_2015_installed_capacity_hydro_mw", "actual_2015_installed_capacity_geothermal_mw",
                    "actual_2015_installed_capacity_mixed_mw",
                    "actual_2015_additional_passengers_upon_implementation_passengers_per_day",
                    "actual_2015_energy_savings_annual_gwh_yr", "cumulative_ghg_reductions_annual_tco2_yr",
                    "cumulative_co_financing_total_us_m", "cumulative_co_financing_mdb1_us_m",
                    "cumulative_co_financing_govt_us_m", "cumulative_co_financing_pvt_us_m",
                    "cumulative_co_financing_bilateral_us_m", "cumulative_co_financing_others_us_m",
                    "cumulative_installed_capacity_total_mw", "cumulative_installed_capacity_wind_mw",
                    "cumulative_installed_capacity_solar_mw", "cumulative_installed_capacity_hydro_mw",
                    "cumulative_installed_capacity_geothermal_mw", "cumulative_installed_capacity_mixed_mw",
                    "cumulative_additional_passengers_upon_implementation_passengers_per_day",
                    "cumulative_energy_savings_annual_gwh_yr", 'ry']
